In [1]:
import pandas as pd 
import numpy as np

In [3]:
order=pd.read_csv('new_list_of_order.csv')
details=pd.read_csv('New_order_details.csv')
target=pd.read_csv('new_sales_target.csv')

In [4]:
order.head()

  Order ID  Order Date CustomerName           State       City
0  B-25601  01-04-2018       Bharat         Gujarat  Ahmedabad
1  B-25602  01-04-2018        Pearl     Maharashtra       Pune
2  B-25603  03-04-2018        Jahan  Madhya Pradesh     Bhopal
3  B-25604  03-04-2018       Divsha       Rajasthan     Jaipur
4  B-25605  05-04-2018      Kasheen     West Bengal    Kolkata

In [5]:
details.head()

  Order ID  Amount  Profit  Quantity     Category      Sub-Category
0  B-25601  1275.0 -1148.0         7    Furniture         Bookcases
1  B-25601    66.0   -12.0         5     Clothing             Stole
2  B-25601     8.0    -2.0         3     Clothing       Hankerchief
3  B-25601    80.0   -56.0         4  Electronics  Electronic Games
4  B-25602   168.0  -111.0         2  Electronics            Phones

In [6]:
target.head()

  Month of Order Date   Category   Target
0              Apr-18  Furniture  10400.0
1              May-18  Furniture  10500.0
2              Jun-18  Furniture  10600.0
3              Jul-18  Furniture  10800.0
4              Aug-18  Furniture  10900.0

In [7]:
order.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 5 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   Order ID      10000 non-null  object
 1   Order Date    10000 non-null  object
 2   CustomerName  10000 non-null  object
 3   State         10000 non-null  object
 4   City          10000 non-null  object
dtypes: object(5)
memory usage: 390.8+ KB

In [8]:
details.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5000 entries, 0 to 4999
Data columns (total 6 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   Order ID      5000 non-null   object
 1   Amount        5000 non-null   float64
 2   Profit        5000 non-null   float64
 3   Quantity      5000 non-null   int64
 4   Category      5000 non-null   object
 5   Sub-Category  5000 non-null   object
dtypes: float64(2), int64(1), object(3)
memory usage: 234.5+ KB

In [9]:
target.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 3 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   Month of Order Date  1000 non-null   object
 1   Category             1000 non-null   object
 2   Target               1000 non-null   float64
dtypes: float64(1), object(2)
memory usage: 23.6+ KB

In [11]:
order.dtypes

Order ID        object
Order Date      object
CustomerName    object
State           object
City            object
dtype: object

In [12]:
details.dtypes

Order ID         object
Amount          float64
Profit          float64
Quantity          int64
Category         object
Sub-Category     object
dtype: object

In [13]:
target.dtypes

Month of Order Date     object
Category                object
Target                 float64
dtype: object

In [22]:
order.isnull().sum()

Month of Order Date    0
Category               0
Target                 0
dtype: int64

In [23]:
details.isnull().sum()

Order ID        0
Amount          0
Profit          0
Quantity        0
Category        0
Sub-Category    0
dtype: int64

In [25]:
target.isnull().sum()

Month of Order Date    0
Category               0
Target                 0
dtype: int64

In [19]:
order.duplicated().sum()
details.duplicated().sum()
target.duplicated().sum()

np.int64(0)

In [32]:
print('unique state')
print(order['State'].unique())

unique state
['Gujarat' 'Maharashtra' 'Madhya Pradesh' 'Rajasthan' 'West Bengal'
 'Karnataka' 'Jammu and Kashmir' 'Tamil Nadu' 'Uttar Pradesh' 'Bihar'
 'Kerala ' 'Punjab' 'Haryana' 'Himachal Pradesh' 'Sikkim' 'Goa' 'Nagaland'
 'Andhra Pradesh' 'Delhi']

In [33]:
print('unique categories')
print(details['Category'].unique())

unique categories
['Furniture' 'Clothing' 'Electronics']

In [35]:
print('sub-categories')
print(details['Sub-Category'].unique())

sub-categories
['Bookcases' 'Stole' 'Hankerchief' 'Electronic Games' 'Phones' 'Saree'
 'Trousers' 'Chairs' 'Kurti' 'T-shirt' 'Shirt' 'Leggings' 'Tables'
 'Printers' 'Accessories' 'Furnishings' 'Skirt']

In [36]:
order.describe()

       Order ID  Order Date CustomerName           State        City
count     10000       10000        10000           10000       10000
unique    10000        2740          332              19          24
top     B-35584  04-12-2018        Nirja  Madhya Pradesh  Chandigarh
freq          1          15           48             598         799

In [37]:
details.describe()

            Amount       Profit     Quantity
count  5000.000000  5000.000000  5000.000000
mean   1845.212956    90.770762     4.968600
std    1589.827507   495.822033     2.815031
min       4.000000 -1981.000000     1.000000
25%     281.942500   -94.640000     3.000000
50%    1549.365000    16.000000     5.000000
75%    3196.775000   270.805000     7.000000
max    5729.000000  1978.550000    14.000000

In [43]:
order['Order Date'].head(10)

0    01-04-2018
1    01-04-2018
2    03-04-2018
3    03-04-2018
4    05-04-2018
5    06-04-2018
6    06-04-2018
7    08-04-2018
8    09-04-2018
9    09-04-2018
Name: Order Date, dtype: object

In [44]:
#convert order date object to date type 
order['Order Date']=pd.to_datetime(
    order['Order Date'],dayfirst=True)

In [45]:
order['Order Date'].head(10)

0   2018-04-01
1   2018-04-01
2   2018-04-03
3   2018-04-03
4   2018-04-05
5   2018-04-06
6   2018-04-06
7   2018-04-08
8   2018-04-09
9   2018-04-09
Name: Order Date, dtype: datetime64[ns]

In [46]:
order["Order Date"] = pd.to_datetime(order["Order Date"])

In [47]:
order.dtypes

Order ID                object
Order Date      datetime64[ns]
CustomerName            object
State                   object
City                    object
dtype: object

In [50]:
#remove dups 
order.drop_duplicates(inplace=True)
details.drop_duplicates(inplace=True) 
target.drop_duplicates(inplace=True)

In [51]:
print("Orders:", order.duplicated().sum())
print("details:", order.duplicated().sum())
print("target:", order.duplicated().sum())

Orders: 0
details: 0
target: 0

In [52]:
#check missing values
print(order.isnull().sum())
print(details.isnull().sum())
print(target.isnull().sum())

Order ID        0
Order Date      0
CustomerName    0
State           0
City            0
dtype: int64
Order ID        0
Amount          0
Profit          0
Quantity        0
Category        0
Sub-Category    0
dtype: int64
Month of Order Date    0
Category               0
Target                 0
dtype: int64

In [53]:
#check negative sale 
details[details['Amount']>0]

     Order ID   Amount   Profit  Quantity     Category      Sub-Category
0     B-25601  1275.00 -1148.00         7    Furniture         Bookcases
1     B-25601    66.00   -12.00         5     Clothing             Stole
2     B-25601     8.00    -2.00         3     Clothing       Hankerchief
3     B-25601    80.00   -56.00         4  Electronics  Electronic Games
4     B-25602   168.00  -111.00         2  Electronics            Phones
...       ...      ...      ...       ...          ...               ...
4995  B-30088  3887.84  -973.42         6     Clothing             Shirt
4996  B-28975  3472.84   166.63         8    Furniture         Bookcases
4997  B-35228  2540.54    33.41         8     Clothing       Hankerchief
4998  B-28016  4201.83  -451.47        10     Clothing           T-shirt
4999  B-26291  1371.77  -381.86         1    Furniture       Furnishings

[5000 rows x 6 columns]

In [55]:
details[details['Quantity']<=0]

Empty DataFrame
Columns: [Order ID, Amount, Profit, Quantity, Category, Sub-Category]
Index: []

In [59]:
details.sort_values('Amount',ascending=False).head(10)

     Order ID   Amount   Profit  Quantity     Category      Sub-Category
1356  B-26055  5729.00    64.00        14    Furniture            Chairs
2149  B-30718  4997.46 -1359.89        10  Electronics  Electronic Games
1797  B-27347  4997.09  -448.28         7  Electronics  Electronic Games
2194  B-29379  4996.56   869.57         2     Clothing             Skirt
2826  B-35151  4995.60  1114.73         3     Clothing           T-shirt
3938  B-32185  4992.40   471.21        10    Furniture         Bookcases
4211  B-34441  4991.59  -260.01         2     Clothing             Kurti
3567  B-33828  4989.26  1892.11         6     Clothing             Stole
2373  B-27129  4988.18  1681.71         1     Clothing             Skirt
4342  B-27594  4987.46  1064.82         6    Furniture            Tables

In [60]:
details.sort_values('Profit').head(10)

     Order ID   Amount   Profit  Quantity     Category      Sub-Category
589   B-25798  2830.00 -1981.00        13    Furniture         Bookcases
22    B-25608  1364.00 -1864.00         5    Furniture            Tables
2566  B-27641  4706.25 -1410.95         9  Electronics          Printers
2293  B-32520  4911.07 -1405.91         6  Electronics       Accessories
1911  B-34675  4733.43 -1402.78         8    Furniture            Chairs
4739  B-29546  4878.04 -1400.52         2     Clothing             Kurti
3846  B-35487  4648.23 -1388.16         5  Electronics  Electronic Games
2793  B-29583  4908.53 -1382.57        10  Electronics          Printers
3380  B-34408  4655.19 -1378.65         5     Clothing          Leggings
2227  B-35243  4692.46 -1367.59         3    Furniture       Furnishings

In [61]:
#check the ordeer id 
missing_orders=details.loc[
    ~details['Order ID'].isin(order['Order ID'])
]
print("Missing Order IDs:", len(missing_orders))
missing_orders.head()

Missing Order IDs: 0

Empty DataFrame
Columns: [Order ID, Amount, Profit, Quantity, Category, Sub-Category]
Index: []

In [65]:
#standardize txt column 
order['State']=order['State'].str.title().str.strip()
order['City']=order['City'].str.title().str.strip()

details["Category"] = details["Category"].str.title().str.strip()
details["Sub-Category"] = details["Sub-Category"].str.title().str.strip()

In [66]:
#create new feature 
order["Year"] = order["Order Date"].dt.year

In [67]:
order["Month"] = order["Order Date"].dt.month_name()

In [68]:
order["Month Number"] = order["Order Date"].dt.month

In [69]:
order["Day"] = order["Order Date"].dt.day_name()

In [70]:
order.head()

,Order ID,Order Date,CustomerName,State,City,Year,Month,Month Number,Day
0,B-25601,2018-04-01,Bharat,Gujarat,Ahmedabad,2018,April,4,Sunday
1,B-25602,2018-04-01,Pearl,Maharashtra,Pune,2018,April,4,Sunday
2,B-25603,2018-04-03,Jahan,Madhya Pradesh,Bhopal,2018,April,4,Tuesday
3,B-25604,2018-04-03,Divsha,Rajasthan,Jaipur,2018,April,4,Tuesday
4,B-25605,2018-04-05,Kasheen,West Bengal,Kolkata,2018,April,4,Thursday

In [71]:
sales=pd.merge(
    order,details,
    on='Order ID',
    how='inner' 
)
sales.head()

,Order ID,Order Date,CustomerName,State,City,Year,Month,Month Number,Day,Amount,Profit,Quantity,Category,Sub-Category
0,B-25601,2018-04-01,Bharat,Gujarat,Ahmedabad,2018,April,4,Sunday,1275.0,-1148.0,7,Furniture,Bookcases
1,B-25601,2018-04-01,Bharat,Gujarat,Ahmedabad,2018,April,4,Sunday,66.0,-12.0,5,Clothing,Stole
2,B-25601,2018-04-01,Bharat,Gujarat,Ahmedabad,2018,April,4,Sunday,8.0,-2.0,3,Clothing,Hankerchief
3,B-25601,2018-04-01,Bharat,Gujarat,Ahmedabad,2018,April,4,Sunday,80.0,-56.0,4,Electronics,Electronic Games
4,B-25602,2018-04-01,Pearl,Maharashtra,Pune,2018,April,4,Sunday,168.0,-111.0,2,Electronics,Phones

In [72]:
sales.shape

(5000, 14)

In [73]:
#profit margin 
sales['Profit Margin (%)']=( 
    sales['Profit']/sales['Amount'])*100

In [75]:
sales['Average Price']=(
    sales['Amount']/sales['Quantity']
)

In [77]:
order.to_csv("Orders_Cleaned.csv", index=False)
details.to_csv("Order_Details_Cleaned.csv", index=False)
sales.to_csv("Retail_Sales_Cleaned.csv", index=False)